### ISSUE TITLE
請補一個檔 (AS 全量数据)

### ISSUE THREAD

**Issue by Anson0627** [YumeMichi/honoka-chan#10]
裏面有文件但是空的

**Comment by YumeMichi** [comment]
你这样描述我也不知道什么意思

**Comment by Anson0627** [comment]
簡單來說
https://pan.baidu.com/s/1CDzbtX6d0hgoczNdLCTzqw?pwd=wfzv 
這個連結的文件是空的, 請問可不可以補一個檔 ?

**Comment by Anson0627** [comment]
> 簡單來說
> https://pan.baidu.com/s/1CDzbtX6d0hgoczNdLCTzqw?pwd=wfzv
> 這個連結的文件是空的, 請問可不可以補一個檔 ?

簡單來說
[https://pan.baidu.com/s/1CDzbtX6d0hgoczNdLCTzqw?pwd=wfzv](url)
這個連結的文件是空的, 請問可不可以補一個檔 ?
<img width="1299" alt="PNG_1" src="https://github.com/YumeMichi/honoka-chan/assets/151342933/ed8652bb-2a65-421e-aca9-720ac0b84010">

**Comment by Anson0627** [comment]
> 你这样描述我也不知道什么意思

簡單來說
[https://pan.baidu.com/s/1CDzbtX6d0hgoczNdLCTzqw?pwd=wfzv](https://github.com/YumeMichi/honoka-chan/issues/url)
這個連結的文件是空的, 請問可不可以補一個檔 ?
<img width="1299" alt="PNG_1" src="https://github.com/YumeMichi/honoka-chan/assets/151342933/858eb9d2-be01-458a-b168-64bec1c66069">
