### ISSUE TITLE
運行honoka-chan.exe后程式自動退出

### ISSUE THREAD

**Issue by minorikawafuso** [YumeMichi/honoka-chan#14]
這是在cmd裏運行的結果
![image](https://github.com/YumeMichi/honoka-chan/assets/47047663/5cd1b74b-db0f-4c68-b5f0-e0580704b097)
這是在有管理員權限的cmd裏運行的結果
![image](https://github.com/YumeMichi/honoka-chan/assets/47047663/4b9354bd-aa06-4de7-9229-f87abf7d178f)

這個honoka-chan.exe應該是一個後臺不斷監聽數據的程式對不對？正常情況應該是輸出
`[xorm] [info]  2024/01/28 00:35:04.231983 PING DATABASE sqlite`
後就保持運行狀態不輸出吧？是我缺少了什麽依賴的軟體嗎？比如SQL？
Android客戶端已經修改完畢了，登錄賬戶時會顯示“系统错误，appid不存在”

**Comment by YumeMichi** [comment]
你默认80端口是不是被占用了

**Comment by minorikawafuso** [comment]
> 你默认80端口是不是被占用了

非常感谢，已排查是Internet Information Services服务占用了80端口
