### ISSUE TITLE
[Enhancement] 建议把 sqlite 驱动换成 CGO-free 的实现

### ISSUE THREAD

**Issue by winooxx** [YumeMichi/honoka-chan#4]
因为现在用的 mattn 这个需要 CGO，在 Windows 下还需要额外多装一套 GCC 才能编译，比较麻烦。
感觉换成[modernc.org/sqlite](https://pkg.go.dev/modernc.org/sqlite@v1.22.1)也不错，xorm 的话应该可以直接替换。

**Comment by YumeMichi** [comment]
试了一下应该ok
