### ISSUE TITLE
multipart 解析处理有误

### ISSUE THREAD

**Issue by winooxx** [YumeMichi/honoka-chan#8]
c85ddda2284377199ac13c6f89a5202f0a55fc67 这个 commit 会导致 main.php/download/additional 接口在解析客户端传来的  `Content-Type: multipart/form-data`  类型的数据时，出现 unexpected end of JSON input （即 JSON 反序列化失败）的错误 。回退到 39bd746d3690439a07daed3d21a7d1d4e6ebd9c4 后 bug 消失。

**Comment by YumeMichi** [comment]
安卓还是iOS？

**Comment by winooxx** [comment]
> 安卓还是iOS？

Android

**Comment by YumeMichi** [comment]
最新的提交已经修复，就是更新有点大，你可以直接修改router.go中的`m.POST("/download/additional", handler.DownloadAdditional)`为`m.POST("/download/additional", middleware.ParseMultipartForm, handler.DownloadAdditional)`

**Comment by winooxx** [comment]
bug 已确认在 commit 81e97cf997c87197ace9d1cd51ff66768f998a91 中修复，相关修复改动位置见 https://github.com/YumeMichi/honoka-chan/issues/8#issuecomment-1642380553
